name: Render Content Farm RealSolve

on:
  # Запуск вручную через GitHub UI
  workflow_dispatch:
      
  # Автозапуск при push в main
  push:
    branches: [ main ]
    paths: [ 'src/**' ]

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install
        npm install typescript @types/node
        echo "✅ Зависимости установлены успешно"
        
    - name: Render video
      run: |
        echo "📁 Проверяем структуру файлов:"
        ls -la src/
        echo "🎬 Проверяем композиции:"
        npx remotion compositions src/Root.tsx || true
        echo "🚀 Начинаем рендер:"
        mkdir -p output
        npx remotion render src/Root.tsx ZyraRealSolve output/github-render.mp4 --overwrite --log=verbose
          
    - name: Upload rendered video
      uses: actions/upload-artifact@v4
      with:
        name: zyra-realsolve-${{ github.run_number }}
        path: output/github-render.mp4
        retention-days: 7
        
    - name: Show result
      run: |
        echo "✅ Рендер завершен!"
        echo "📁 Видео доступно в Artifacts"
        ls -la output/
